//------------------------------------------------------------------------
// Copyright(c) 2024 NarDSP.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"TanAlias.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"TanAlias VST3 (64Bit)"
#else
#define stringFileDescription	"TanAlias VST3"
#endif
#define stringCompanyName		"NarDSP\0"
#define stringLegalCopyright	"Copyright(c) 2024 NarDSP."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
